name: Matrix Jobs from Variable

on:
  push:

jobs:
  list-files:
    outputs: 
      bicep-files: ${{ steps.list-files.outputs.files }}
    runs-on: ubuntu-latest
    steps:
      - name: list-files
        id: list-files
        run: |
          mkdir files
          touch files/file1
          touch files/file2
          touch files/file3
          echo files=$(ls files | jq -R -s -c 'split("\n")[:-1]') >> $GITHUB_OUTPUT

  test_matrix:
    needs: [list-files]
    strategy:
      matrix:
        file: ${{ fromJson(needs.list-files.outputs.bicep-files) }}
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo running on ${{ matrix.file }} 
