name: Matrix Jobs

on:
  push:

jobs:
  list-files:
    outputs: 
      bicep-files: ${{ steps.list-files.outputs.files }}
      files2: ${{ steps.list-files.outputs.files2 }}
    runs-on: ubuntu-latest
    steps:
      - name: list-files
        id: list-files
        run: |
          mkdir files
          touch files/file1
          touch files/file2
          touch files/file3
          echo $(ls files | jq -R -s -c 'split("\n")[:-1]')
          echo files=\'$(ls files | jq -R -s -c 'split("\n")[:-1]')\' >> GITHUB_OUTPUT
          echo files2=[1,2,3] >> GITHUB_OUTPUT

  output:
    needs: [list-files]
    runs-on: ubuntu-latest
    steps:
      - name: test
        env: 
          FILES: ${{ needs.list-files.outputs.files2 }}
          BICEP: ${{ needs.list-files.outputs.bicep-files }}
        run: |
          echo $BICEP
          echo $FILES


  test_matrix:
    needs: [list-files]
    strategy:
      matrix:
        file: ${{ fromJson(needs.list-files.outputs.bicep-files) }}
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo running on ${{ matrix.file }} 
